# Generated by Django 4.0.4 on 2022-05-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_slug_profile_user_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='default.png', upload_to='banners'),
        ),
    ]
