# Generated by Django 4.0.4 on 2022-05-11 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('massanger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MassangerModels',
            new_name='MassangerModel',
        ),
    ]
