# Generated by Django 4.0.4 on 2022-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massanger', '0002_rename_massangermodels_massangermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='massangermodel',
            name='SendTo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='massangermodel',
            name='Text',
            field=models.TextField(default=' '),
        ),
    ]
