# Generated by Django 4.0.4 on 2022-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_exchange_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
