# Generated by Django 4.0.4 on 2022-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_alter_exchange_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='technologies',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
