# Generated by Django 4.0.4 on 2022-05-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
